// Generated output permission: see OUTPUT-EXCEPTION.md at the project root.
import { quasiStaticBlocker } from './access-types.js'
import { buildRegisterModel } from './csr-rtl.js'

/**
 * Timing exceptions for the fields marked quasi-static.
 *
 * Most of a CSR block is written once, early, and then held still: a mode
 * select, a threshold, a base address. Nothing downstream is running yet when
 * the value lands, and it does not move again, so the path from the field flop
 * to whatever it configures never has to meet timing. Leaving those paths in
 * the graph only produces violations nobody can fix. Ticking a field lists it
 * here and the path is cut.
 *
 * Quasi-static is a claim about the value, not about the clocks: it is what
 * makes cutting a multi-bit field safe, since a field that never moves while
 * it is being read cannot be caught half-updated.
 *
 * Only the field's own flop is cut, with -from, which is the one thing the
 * claim covers. Cutting at the launch flop also leaves the host's write path
 * into it timed as normal. Whatever hardware drives back into the block - an
 * RO value, a W1C set strobe - moves on its own schedule and is nobody's idea
 * of quasi-static, so it stays in the timing graph and wants a synchroniser
 * rather than an exception.
 */

/**
 * What the same exception has to look like per toolchain. Three things move:
 * how hierarchy is spelled, which collection command finds a flop, and what
 * synthesis called the flop once it had made it.
 *
 * Getting any of them wrong is quiet rather than loud - the pattern matches
 * nothing and the path stays timed - so this is a choice worth making
 * explicitly rather than defaulting into.
 */
export const SDC_TARGETS = {
  synopsys: {
    label: 'Synopsys / Vivado',
    separator: '/',
    collection: 'get_cells',
    // Synthesis appends _reg to the flop it infers from a signal.
    regSuffix: '_reg',
    note: 'Design Compiler, PrimeTime and Vivado',
  },
  quartus: {
    label: 'Intel Quartus',
    separator: '|',
    // Quartus keeps registers in their own collection, and names each one
    // after the signal it came from with nothing appended.
    collection: 'get_registers',
    regSuffix: '',
    note: 'Quartus Prime, TimeQuest',
  },
}

export const DEFAULT_SDC_TARGET = 'synopsys'

export const resolveSdcTarget = (name) =>
  SDC_TARGETS[name] ?? SDC_TARGETS[DEFAULT_SDC_TARGET]

/** The bridged interfaces instantiate the CSR block one level down, as u_csr. */
const BLOCK_INSTANCE = 'u_csr'

/** Instance-path variable the emitted constraints are written against. */
const INST_VAR = 'csr_inst'
const BLOCK_VAR = 'csr_block'

/** How a field labels itself in a comment: REG[].FIELD (RW). */
const fieldLabel = (reg, field) =>
  `${reg.name}${reg.array ? '[]' : ''}.${field.name} (${field.access})`

/**
 * The exception one field needs, or the reason it needs none. An eligible
 * field is cut at its own flop. The editor only offers the tick on the types
 * that can carry it, so a blocked one here came from an older document or a
 * hand-edited file; it is reported rather than honoured, since emitting the
 * cut anyway is how a strobe quietly stops being timed.
 */
const fieldException = (reg, field, target) => {
  const label = fieldLabel(reg, field)
  const blocker = quasiStaticBlocker(field.access)

  if (blocker) {
    return {
      comment: `${label}: ${field.constant ? 'constant, tied off inside the block - nothing to cut' : blocker}`,
      constraint: null,
    }
  }

  return {
    comment: `${label}: quasi-static, not timed to its consumers`,
    constraint:
      `set_false_path -from [${target.collection} ` +
      `$${BLOCK_VAR}${target.separator}${field.sig}_o${target.regSuffix}*]`,
  }
}

/** Fields the document has ticked, in address then bit order. */
export const quasiStaticFields = (model) =>
  model.regs.flatMap((reg) =>
    reg.fields
      .filter((field) => field.quasiStatic)
      .sort((a, b) => a.lsb - b.lsb)
      .map((field) => ({ reg, field }))
  )

const renderSdc = (model, target) => {
  const bridged = model.interface !== 'Native'
  const marked = quasiStaticFields(model)

  const lines = [
    `# ${model.moduleName}.sdc`,
    '#',
    '# Timing exceptions for the CSR fields marked quasi-static.',
    `# Written for ${target.label} (${target.note}) - the object names below`,
    '# follow its conventions, so re-generate if you change synthesis tool.',
    '# Generated by csr-editor - source it after the clocks are created.',
    '#',
    '# Each field listed below is written before the logic it configures runs,',
    '# and held still afterwards. A field that moves during operation does not',
    '# belong in this file.',
    '',
    '# Instance path of the CSR block. Edit it, or set it before sourcing this',
    '# file, so it names the instance in your design.',
    `if {![info exists ${INST_VAR}]} {`,
    `    set ${INST_VAR} "u_${model.moduleName.toLowerCase()}"`,
    '}',
    '',
  ]

  if (bridged) {
    lines.push(
      `# The ${model.interface} build wraps the register block in a bridge, so the field`,
      `# flops sit one level below $${INST_VAR}.`,
      `set ${BLOCK_VAR} "$${INST_VAR}${target.separator}${BLOCK_INSTANCE}"`,
      ''
    )
  } else {
    lines.push(`set ${BLOCK_VAR} "$${INST_VAR}"`, '')
  }

  if (marked.length === 0) {
    lines.push(
      '# No field is marked quasi-static, so there is nothing to cut.',
      '# Tick a field in the editor to have it constrained here.',
      ''
    )

    return lines.join('\n')
  }

  let currentReg = null

  for (const { reg, field } of marked) {
    if (reg !== currentReg) {
      lines.push(
        `# ---- ${reg.name} @ 0x${reg.addr.toString(16).toUpperCase().padStart(4, '0')} ----`
      )
      currentReg = reg
    }

    const { comment, constraint } = fieldException(reg, field, target)
    lines.push(`# ${comment}`)

    // A field can be worth a note without being worth a constraint.
    if (constraint) {
      lines.push(constraint)
    }

    lines.push('')
  }

  return lines.join('\n')
}

/**
 * The SDC the document generates, in the same shape the RTL generator returns,
 * so the two viewers can share their file list handling.
 */
export const generateSdcFiles = (doc) => {
  const model = buildRegisterModel(doc?.params, doc?.registers)
  const target = resolveSdcTarget(doc?.params?.sdcTarget)

  return [
    {
      name: `${model.moduleName}.sdc`,
      content: renderSdc(model, target),
    },
  ]
}

/** How many fields the document would constrain, for the editor to show. */
export const countQuasiStaticFields = (registers = {}) =>
  Object.values(registers).reduce(
    (total, reg) =>
      total + (reg?.fields ?? []).filter((field) => field?.quasiStatic).length,
    0
  )
